### ISSUE TITLE
slack fun

### ISSUE THREAD

**Issue by stringertheory** [datascopeanalytics/fun#11]
Perhaps an annoying message/quote sent to person/room at random time intervals? Something like "Dean", "Dean", "Dean", "Dean", "Dean", "Hi Dean", "Dean" sent to Dean every 5-10 seconds?

**Comment by deanmalmgren** [comment]
I'm pretty glad that slack stops counting at 9 unread messages:

<img width="195" alt="screen shot 2015-09-21 at 3 13 50 pm" src="https://cloud.githubusercontent.com/assets/255672/10003700/77a8ac0a-6073-11e5-8436-9cac23e49b03.png">
