### ISSUE TITLE
dropbox fun!

### ISSUE THREAD

**Issue by stringertheory** [datascopeanalytics/fun#5]

**Comment by bjlange** [comment]
![clapping](https://cloud.githubusercontent.com/assets/780375/7383138/ef4fd69c-ede7-11e4-9d86-a29cf21e083a.gif)

**Comment by stringertheory** [comment]
Hahaha. That is one intense clapper.

**Comment by laurieskelly** [comment]
Mike on the internet must feel like the first time you travel abroad, every
time.

"What are these smells? I can't understand what anyone is saying! What kind
of money is this? How marvelous!"
